# new line between prompt
add_newline = false

right_format = "$status"

# Use custom format
format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$cobol\
$container\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$cmd_duration\
$fill\
$time\
$line_break\
$jobs\
$character
"""

# prompt character
[character]
success_symbol = "[❯](2)"

[username]
format = "[$user]($style)"
style_user = "6 bold"
style_root = "6 bold"
show_always = true

[hostname]
ssh_only = false
format = "@[$hostname](bold 5) "
disabled = false

[directory]
style = "bold 14"
truncation_length = 3
truncation_symbol = "…/"

[time]
disabled = false
format = ' [ $time]($style)'
style = "bold 3"
utc_time_offset = "+1"

[fill]
style = "8"

[status]
style = "fg:1"
sigint_symbol="✘"
format = '[$symbol $common_meaning$signal_name$maybe_int]($style)'
map_symbol = true
disabled = false
